name: Build X00LDB with KSU
on:
  workflow_dispatch:
  
jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Build Kernel
      uses: nivranaitsirhc/Android_Kernel_Builder@continues-changes
      with:
          # Kernel Config
          arch: arm64
          kernel-url: https://github.com/nivranaitsirhc/android_kernel_asus_msm8937
          kernel-branch: master
          
          # defconfig: vendor/asus/X01BD-KSU_defconfig
          defconfig: X00LDA_defconfig

          use-clang: true
          use-aosp-clang: true
          aosp-clang-branch: android-9.0.0_r61 # android10-d4-release
          aosp-clang-version: clang-4691093 # clang-r353983d
          #custom-clang-url: https://github.com/ZyCromerZ/Clang/releases/download/21.0.0git-20250314-release/Clang-21.0.0git-20250314.tar.gz
          #custom-clang-branch: 

          use-gcc: true
          use-aosp-gcc: true
          aosp-gcc-branch: android-9.0.0_r61 # android10-d4-release
          #custom-gcc-url:
          #custom-gcc-branch:

          # Build Config
          use-ccache: true
          show-ccache-stats: true
          #extended-build-commands: LD=ld.lld AR=llvm-ar AS=llvm-as NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip ANDROID_SILENT_DEPRECATION=true
          
          # KernelSU Support & others
          use-ksu: false
          ksu-version: main
          ksu-url-setup: https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh
          
          # Extras
          use-anykernel3: true
          
          use-release: true
          release-name: X00LDA-KSU
          # use-extended-rel-name: true
          access-token: ${{ secrets.GHT }}
