name: Build X01BD PE-13 with KSU
on:
  workflow_dispatch:
  
jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/nivranaitsirhc/kernel_asus_sdm660-PixelExperience
          kernel-branch: thirteen
          config: asus/X01BD_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          aosp-clang-version: r450784d
          android-version: ""
          # set to false due kernel_build_actions re-patching namespace.c
          ksu: false
          ksu-other: true
          ksu-url: https://github.com/rsuntk/KernelSU
          anykernel3: true
          # set to false due to ccache causing errors with clang
          ccache: false
          # setup release
          release: true
          #release-name: X01BD-Twilight
          #release-name-ksu-info: true
          #release-name-kernel: true
          #release-name-kernel-sha: true
          access-token: ${{ secrets.GHT }}
