name: Build X01BD rsuntk-KSU @master
on:
  workflow_dispatch:
  
jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: nivranaitsirhc/kernel_build_action@nivranaitsirhc-patch-fix_ccache_implementation
      with:
          kernel-url: https://github.com/nivranaitsirhc/android_kernel_asus_sdm660-4.19
          kernel-branch: Twilight
          config: asus/X01BD-Twilight_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          aosp-clang-version: r530567
          android-version: ""
          # set to false due kernel_build_actions re-patching namespace.c
          ksu: false
          ksu-other: true
          ksu-url: https://github.com/rsuntk/KernelSU
          anykernel3: true
          # set to false due to ccache causing errors with clang
          ccache: false
          # setup release
          release: true
          access-token: ${{ secrets.GHT }}
